kafka:
  enabled: true
  groupId: qad
  clientId: qad
  bootstrap:
    servers: ${KAFKA_ENDPOINT:processing.envirocar.org:9092}

qad:
  simplifyLengthCalculation: ${QAD_SIMPLIFY_LENGTH_CALCULATION:false}
  maxAngleDeviation: ${QAD_MAX_ANGLE_DEVIATION:45}
  maxLengthDeviation: ${QAD_MAX_LENGTH_DEVIATION:0.30}
  lengthDifferenceToTolerate: ${QAD_LENGTH_DIFFERENCE_TO_TOLERATE:10}
  snappingTolerance: ${QAD_SNAPPING_TOLERANCE:50}
  stops:
    startThresholdSpeed: ${QAD_STOP_START_THRESHOLD:5.0}
    endThresholdSpeed: ${QAD_STOP_END_THRESHOLD:10.0}
  segments:
    bufferSize: ${QAD_SEGMENT_BUFFER_SIZE:10}
  densify:
    numPoints: ${QAD_DENSIFY_NUM_POINTS:4}
  mapMatching:
    enabled: ${QAD_MAPMATCHING_ENABLE:true}
    url: ${QAD_MAPMATCHING_ENDPOINT:https://processing.envirocar.org}
  uturn:
    windowSize: ${QAD_UTURN_WINDOW_SIZE:45}
    bufferSize: ${QAD_UTURN_BUFFER_SIZE:20}
    minAngleDeviation: ${QAD_UTURN_MIN_ANGLE_DEVIATION:170}
  outputPath: ${QAD_OUTPUT_PATH:/tmp}
  spring:
    output:
      ansi:
        enabled: true



logging:
  level:
    root: info
    org:
      envirocar: debug