package org.envirocar.qad;

public interface JsonConstants {

    String ID = "id";
    String MATCHED_ROUTE = "matchedRoute";
    String MATCHED_POINTS = "matchedPoints";
    String OSM_ID = "osmId";
    String POINT_ON_ROAD = "pointOnRoad";
    String UNMATCHED_POINT = "unmatchedPoint";
    String STREET_NAME = "streetName";
    String MEASUREMENT_ID = "measurementId";
    String VALUE = "value";
    String PHENOMENONS = "phenomenons";
    String TIME = "time";
    String SEGMENTS = "segments";
    String CITY = "city";
    String AXIS = "axis";
    String START = "start";
    String END = "end";
    String FUEL_TYPE = "fuelType";
    String SEGMENT_ID = "segmentId";
    String SEGMENT_LENGTH = "segmentLength";
    String TRAVEL_TIME = "travelTime";
    String STOPS = "stops";
    String STOPPED_TIME = "stoppedTime";
    String FUEL_CONSUMPTION = "fuelConsumption";
    String ENERGY_CONSUMPTION = "energyConsumption";
    String EMISSION = "emission";
    String SPEED = "speed";
    String NAME = "name";
    String VERSION = "version";
    String SEGMENT_TYPE = "type";
    String SEGMENT_RANK = "rank";
    String AXIS_ID = "axis";
    String AXIS_DIRECTION = "direction";
    String MAX_SPEED = "maxSpeed";
    String TRAFFIC_LIGHT = "LSA";
    String SENSOR = "sensor";
    String PROPERTIES = "properties";
    String FEATURES = "features";
    String TYPE = "type";
    String GEOMETRY = "geometry";
    String UNIT = "unit";
    String TRACK = "track";
    String BEGIN = "begin";
    String LENGTH = "length";
    String TRACKS = "tracks";
}
